### PR TITLE
Check voice channel permissions

### LINKED ISSUE #11: Consider validating channel permissions before registering activity
It has been suggested that the `voiceStateUpdate` event fires even for channels that a bot doesn't have access to. If this is the case we should validate view access to a voice channel before processing an update as activity.

### PR DESCRIPTION
**Pull request by oliver4888**
Checks if the bot has the [VIEW_CHANNEL](https://discord.js.org/#/docs/main/stable/class/Permissions?scrollTo=s-FLAGS) permission before calling `ActivityRegisterer::registerActivity`.

Fixes #11

### CODE REVIEW

**Comment by benji7425** [comment]
Have you confirmed that this is indeed a bug? Seems like quite the oversight on Discord's part if users/bots are able to learn about channels that are meant to be hidden from them. Users might be hiding in invisible mode from other users or something.

**Comment by oliver4888** [comment]
I haven't reported anything to them as of yet (I did see a Github repo for issues with the Discord API). Although I did some testing with a bot that would log whenever it received a voice state update along with whether it's permissions would let it access that channel. From that I could see that the bot would get the voice state update notifications even in channels that it shouldn't be able to access.

**Comment by benji7425** [comment]
Hmm, okay. I will test it myself to see if I can replicate the behaviour too.

**Comment by benji7425** [comment]
Ok, I can replicate this as well. Have you submitted an issue to Discord?

**Comment by benji7425** [comment]
I think I will include this update into disharmony's voiceStateUpdate in case I end up using this anywhere else. I can't imagine any situation where I'd want one of my bots to see a channel it wasn't allowed to.

**Comment by benji7425** [comment]
Transferred to [disharmony #16](https://github.com/benji7425/disharmony/issues/16) and included in 80bebb08b3dca0f5246e3a8c188118bfd3f578c7

**Pull request closed without merging**
